version: 2
updates:
  - package-ecosystem: "gradle" # Use Maven profile
    directory: "/nodehistj-today-nodelist" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle" # Use Maven profile
    directory: "/nodelistj-download-nodelists" # Location of package manifests
    schedule:
      interval: "daily"